// export const API = 'http://localhost:5050'
export const API = 'https://yogurt13-api.onrender.com'
export const AUTH_API = API + '/auth/'
export const PROFILE_API = API + '/profile/'
export const COCKTAILS_API = API + '/cocktail/'
export const CART_API = API + '/cart/'
export const FAVORITE_API = API + '/favorite/'
export const REGISTER_API = AUTH_API + 'register'
export const LOGIN_API = AUTH_API + 'login'
export const GET_PROFILE_API = PROFILE_API + 'user'
export const PROFILE_EDIT_API = PROFILE_API + 'user-edit'
export const PROFILE_DELETE_API = PROFILE_API + 'user-delete'

export const GET_COCKTAILS_API = COCKTAILS_API + 'get-all-products'
export const ADD_PRODUCT_TO_CART_API = CART_API + 'add-to-cart/:productId'
export const GET_PRODUCT_CART_API = CART_API + 'get-cart-products'
export const GET_PRODUCT_FAVORITE_API = FAVORITE_API + 'get-favorites'
export const GET_CATEGORY_PRODUCT_API = COCKTAILS_API + 'get-category-products'
